services:
  dx-runtime:
    container_name: dx-runtime_intel-hw-acc-${BASE_IMAGE_NAME}-${OS_VERSION}
    image: dx-runtime_intel-hw-acc:${BASE_IMAGE_NAME}-${OS_VERSION}
    build:
      dockerfile: docker/Dockerfile.dx-runtime.intel_gpu_hw_acc

